services:
  nginx:
    build:
      context: ./nginx
    image: nginx:1.21.1-alpine

  php-fpm:
    build:
      context: ./php-fpm
    image: php:7.4-fpm-alpine3.14

  mysql:
    build:
      context: ./mysql
    image: percona:5.7-centos
